# -*- coding: utf-8 -*-
{
    "name": "Beta Extended",
    "version": "8.0.0.11",
    "author": "Nabeel",
    "category": "Purchase",
    "description": """ Purchase Report""",
    "website": "http://www.betait.net",
    "depends": ['purchase', 'orchid_beta', 'beta_invoice', 'hr_holidays', 'mail', 'warning'],
    'data': [
        'data/wfh_mail_templates.xml',
        'data/document_request_email_template.xml',
        'data/commitment_letter_email_template.xml',
        'data/datahut_ms_template.xml',
        'data/employee_contract_expiry_template.xml',
        'data/sequence.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/bank_loan_view.xml',
        'views/product_view.xml',
        'views/partner_view.xml',
        'views/crm_view.xml',
        'views/cost_sheet_view.xml',
        'views/purchase_view.xml',
        'views/employee_view.xml',
        'views/hr_purchase_view.xml',
        'views/picking_view.xml',
        'views/stock_lot_view.xml',
        'views/commitment_letter_view.xml',
        'views/doc_request_view.xml',
        'views/account_payment_term_view.xml',
        'views/wfh_limit.xml',
        'views/work_from_home_view.xml',
        'views/business_trip_view.xml',
        'ps_po_report/wizard/ps_po_report_view.xml',
        'sup_inv_actual_date/views/account_view.xml',
        'wizard/customer_statement_rpt_view.xml',
        'wizard/emp_contract_expiry_view.xml',
        'wizard/doc_refuse_view.xml',
        'views/emp_contract_quarterly_view.xml',
        'report/ksa_external_template.xml',
        'report/po_template.xml',
        'report/po_template_ksa.xml',
        'report/report_action.xml',
    ],
    'demo': [],
    'installable': True,

}
