# -*- coding: utf-8 -*-
{
    "name" : "Beta Customisation",
    "version" : "0.3",
    "author": "Beta Information Technology",
    "category" : "ALL",
    "description": """ Beta Customisations""",
    "website": "http://www.betait.net",
    "depends": ['base', 'crm', 'calendar', 'analytic','orchid_beta_project', 'orchid_cost_sheet', 'account', 'hr','hr_recruitment', 'website', 'orchid_hrms', 'hr_expense'],
    'data': [
        'mail_template.xml',
        'data/mail_template.xml',
        'delivery_req.xml',
             'data/resign_mail_template.xml',
             'data/termination_mail_template.xml',
             'data/role_change_mail.xml',
             'data/planned_inv_rem_mail.xml',
             'data/mail_temp.xml',
             'data/sequence.xml',
             'change/project_view.xml',
             'crm/od_mail_template.xml',
             'change/change_view.xml',
             'change/change_inv_plan_view.xml',
            'crm/assign_presale_wizard_view.xml',
            'crm/crm_lead_view.xml',
            'crm/pre_oprn_view.xml',
            'crm/lost_opp_wiz_rpt_view.xml',
            'crm/lost_opp_brand_rpt_view.xml',
            'crm/named_accounts_view.xml',
            'crm/product_view.xml',
            'crm/in_transition_rpt.xml',
            'crm/organisation_cust_rpt_view.xml',
            'crm/add_contact_view.xml',
            'crm/add_contact_from_partner_view.xml',
            'crm/deactivate_people_from_partner_view.xml',
            'crm/modify_people_from_partner_view.xml',
            'crm/scheduler.xml',
            'crm/lg_request_form_view.xml',
            'crm/tender_request_view.xml',
            'helpdesk/sla_perform_view.xml',
            'helpdesk/amc_om_index_view.xml',
            'helpdesk/uae_service_ot_rpt_view.xml',
            'helpdesk/tech_ticket_approval_view.xml',
            'helpdesk/technicians_bulk_activity_wiz_view.xml',
            'helpdesk/helpdesk_portal_view.xml',
            'helpdesk/customer_visit_report_view.xml',
            'asset/asset_addition_rpt_view.xml',
            'asset/asset_deletion_rpt_view.xml',
            'project/project_view.xml',
            'project/analytic_view.xml',
            'project/bulk_activities_view.xml',
            'project/menu.xml',
            'project/handover_service_view.xml',
            'project/outsource_employee.xml',
            'project/outsourced_emp_joining_form_view.xml',
            'purchase/purchase_view.xml',
            'hr/hr_view.xml',
            'hr/hr_payroll_view.xml',
            'hr/job_view.xml',
            'hr/hr_applicant_view.xml',
            'hr/od_payroll_transactions_view.xml',
            'hr/cost_centre_view.xml',
            'hr/hr_resign_view.xml',
            'hr/hr_terminate_view.xml',
            'hr/hr_role_change_view.xml',
            'hr/hr_holidays_view.xml',
            'hr/res_partner_view.xml',
            'hr/hr_carrier_cert_view.xml',
            'hr/end_of_contract_view.xml',
            'account/invoice_view.xml',
            'account/account_voucher_view.xml',
            'account/trial_balance_view.xml',
            #'product/product_brand_view.xml',
            'wizard/customer_statement_rpt_view.xml',
            'wizard/supplier_statement_rpt_view.xml',
            'wizard/pre_operation_report_view.xml',
            'wizard/invoice_payment_details_view.xml',
            'wizard/pmo_analytic_view.xml',
            'wizard/layout.xml',
            'wizard/amc_rev_rpt_view.xml',
            'wizard/import_po_lines_wiz_view.xml',
            'wizard/gratuity_report_view.xml',
            'bank_loan/bank_loan_view.xml',
            'bank_loan/mail_template.xml',
            'bank_loan/hr_salary_profile_view.xml',
            'bank_loan/close_loan_view.xml',
            'bank_loan/loan_bank_view.xml',
            'bank_loan/beta_loan_view.xml',
            'stock_report/od_stock_aging_report_view.xml',
            'stock_report/report_stock_aging.xml',
            'stock_report/stock_print_view.xml',
            'stock_report_thirty/od_stock_aging_report_view.xml',
            'stock_report_thirty/report_stock_aging1.xml',
            'stock_rpt_xls/od_stock_aging_report_view.xml',
            
            'wizard/csv_import_view.xml',
            'wps_uae/wps.xml',
            'vendor_rpt/brand_rpt_view.xml',
            'controllers/form_fill_template.xml',
            'sale/sale_achievement_rpt_view.xml',
            'analysis_report/account_entries_report_view.xml'
            ],
    'demo': [],
    'installable': True,
  
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
