# -*- coding: utf-8 -*-
{
    "name" : "Orchid Cost Sheet",
    "version" : "0.2.0.0.1",
    "author": "OrchidERP",
    "category" : "",
    "description": """Orchid Cost Sheet""",
    "website": ["http://www.orchiderp.com"],
    "depends": ['base','sale','crm','orchid_product','account',
#                 'orchid_order_type',
                'orchid_cost_centre',
               
                'orchid_so2po',
                
                
              
                ],
    "data" : [  'security/ir.model.access.csv',
                'utl/tabs_data.xml',
                'scheduler.xml',
                'layout.xml',
                'e_invoice_ksa.xml',
                'utl/tab_view.xml',
                'confirm/confirm_view.xml',
                'analytic_view.xml',
                'attachement_view.xml',
                'od_mail_template.xml',
                'gp_approval_mail_temp.xml',
                'mail/mail_template.xml',
                'mail/costsheet_template.xml',
                'mail/material_issue_mail.xml',
                'res_company_view.xml',
                'crm_lead_seq_view.xml',
                'od_cost_sheet_seq_view.xml',
                'wizard/fill_wiz_view.xml',
                'wizard/assign_owner_view.xml',
                'wizard/assign_accountant_view.xml',
                'wizard/material_issue_wiz_view.xml',
                'wizard/confirm_wiz_view.xml',
                'wizard/costgroup_wiz_view.xml',
                'wizard/section_wiz_view.xml',
                'wizard/opp_revenue_rpt_view.xml',
                'wizard/opp_revenue_brand_rpt_view.xml',
                'wizard/sale_in_view.xml',
                'wizard/sale_in_brand_rpt_view.xml',
                'wizard/commit_comp_wiz_view.xml',
                'wizard/lead_analysis_view.xml',
                'wizard/pmo_wiz_view.xml',
                'wizard/import_export_wiz_view.xml',
                'od_cost_sheet_view.xml',
                'sheet_view.xml',
                'import/material_view.xml',
                'import/optional_material_view.xml',
                'import/trn_view.xml',
                'import/eqp_bmn.xml',
                'import/eqp_omn.xml',
                'import/renewal_view.xml',
                'import/renewal_opt_view.xml',
                'crm_lead_view.xml',
                'sale_view.xml',
                'invoice_view.xml',
                 'menu/helpdesk.xml',
                 'change_management/email_template.xml',
                 'change_management/cm_seq.xml',
                 'change_management/change_view.xml',
                'crm/crm_view.xml',
                'crm/inquiry_type.xml',
#                 'report/mat_report_view.xml',
        
            ],
    'css': [],
}
